# 📊 04 - Data Input and Output

Most of data science is about **loading data, exploring it, and saving results**.

This notebook covers:
- Reading CSV files with Pandas
- Inspecting DataFrames (`.head()`, `.info()`, `.describe()`)
- Writing data back to CSV
- Reading Excel files (if available)

## 1. Reading CSV Files

In [1]:
import pandas as pd

# Create a small CSV for demo
data = """Name,Age,Score
Alice,23,90
Bob,25,85
Charlie,22,95
"""
with open('students.csv', 'w') as f:
    f.write(data)

# Read CSV into a DataFrame
df = pd.read_csv('students.csv')
df

      Name  Age  Score
0    Alice   23     90
1      Bob   25     85
2  Charlie   22     95

✅ **Your Turn**: Create your own small CSV (3–5 rows) and read it into Pandas.

In [11]:
# Your turn here
import pandas as pd
retail = """Product, Quantity, Price
Mobile,4,10264
Car,1,35689
Coffee Maker,3,150
"""
with open('Retail_Invoice.csv', 'w') as f:
    f.write(retail)

# Read CSV into a DataFrame
df = pd.read_csv('Retail_Invoice.csv')
df

        Product   Quantity   Price
0        Mobile          4   10264
1           Car          1   35689
2  Coffee Maker          3     150

## 2. Exploring DataFrames

In [12]:
# Look at the first rows
df.head()

        Product   Quantity   Price
0        Mobile          4   10264
1           Car          1   35689
2  Coffee Maker          3     150

In [13]:
# Info about columns and data types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Product    3 non-null      str
 1    Quantity  3 non-null      int64
 2    Price     3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

In [14]:
# Summary statistics
df.describe()

       Quantity         Price
count  3.000000      3.000000
mean   2.666667  15367.666667
std    1.527525  18310.944551
min    1.000000    150.000000
25%    2.000000   5207.000000
50%    3.000000  10264.000000
75%    3.500000  22976.500000
max    4.000000  35689.000000

✅ **Your Turn**: Use `.head()` to preview your own dataset and `.describe()` to see its basic statistics.

In [19]:
# Your turn here
import pandas as pd
retail = """Product, Quantity, Price
Mobile,4,10264
Car,1,35689
Coffee Maker,3,150
"""
with open('Retail_Invoice.csv', 'w') as f:
    f.write(retail)

# Read CSV into a DataFrame
df = pd.read_csv('Retail_Invoice.csv')
df
#df.info()
#df.describe()

        Product   Quantity   Price
0        Mobile          4   10264
1           Car          1   35689
2  Coffee Maker          3     150

In [20]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Product    3 non-null      str
 1    Quantity  3 non-null      int64
 2    Price     3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

       Quantity         Price
count  3.000000      3.000000
mean   2.666667  15367.666667
std    1.527525  18310.944551
min    1.000000    150.000000
25%    2.000000   5207.000000
50%    3.000000  10264.000000
75%    3.500000  22976.500000
max    4.000000  35689.000000

## 3. Writing CSV Files

In [21]:
# Save the DataFrame to a new CSV
df.to_csv('students_copy.csv', index=False)
%ls *.csv

 Volume in drive C has no label.
 Volume Serial Number is D697-85A7

 Directory of c:\Users\Nazmun\Projects\3603-data-science-mansur\Work\02-Working_with_Data\06-Foundations

09/15/2026  10:34 PM                81 example .csv
09/15/2026  10:35 PM                64 example.csv
09/15/2026  10:23 PM                47 pets.csv
09/18/2026  10:19 AM                75 Retail_Invoice.csv
09/15/2026  10:45 PM                30 scores.csv
09/18/2026  10:09 AM                55 students.csv
09/18/2026  10:21 AM                75 students_copy.csv
               7 File(s)            427 bytes
               0 Dir(s)  262,799,343,616 bytes free

✅ **Your Turn**: Save your DataFrame to a CSV file called `my_data.csv`.

In [23]:
# Your turn here
import pandas as pd
retail = """Product, Quantity, Price
Mobile,4,10264
Car,1,35689
Coffee Maker,3,150
"""
with open('Retail_Invoice.csv', 'w') as f:
    f.write(retail)

# Read CSV into a DataFrame
df = pd.read_csv('Retail_Invoice.csv')
df
df.to_csv('my_data.csv', index=False)
%ls *.csv

 Volume in drive C has no label.
 Volume Serial Number is D697-85A7

 Directory of c:\Users\Nazmun\Projects\3603-data-science-mansur\Work\02-Working_with_Data\06-Foundations

09/15/2026  10:34 PM                81 example .csv
09/15/2026  10:35 PM                64 example.csv
09/18/2026  10:22 AM                75 my_data.csv
09/15/2026  10:23 PM                47 pets.csv
09/18/2026  10:22 AM                75 Retail_Invoice.csv
09/15/2026  10:45 PM                30 scores.csv
09/18/2026  10:09 AM                55 students.csv
09/18/2026  10:21 AM                75 students_copy.csv
               8 File(s)            502 bytes
               0 Dir(s)  261,841,215,488 bytes free

## 4. Reading Excel Files
This section needs the `openpyxl` package. If it's not installed in your `.venv`, run `pip install openpyxl` in your terminal first — or just read through this part, it's optional.

In [24]:
# Optional: requires 'openpyxl' installed
# Save to Excel
df.to_excel('students.xlsx', index=False)

# Read Excel file
pd.read_excel('students.xlsx')

ModuleNotFoundError: No module named 'openpyxl'

✅ **Your Turn**: Try saving your dataset to Excel and reading it back (if supported in your environment).

In [ ]:
# Your turn here

---
### Summary
- `pd.read_csv()` loads data into a DataFrame.
- Use `.head()`, `.info()`, `.describe()` to explore quickly.
- `df.to_csv()` and `df.to_excel()` save results.
- Pandas makes file I/O simple and reliable.

## 🏋️ Practice

### Practice 1 — Select a Column (easy)
From `df`, print just the `'Score'` column, then print its average with `.mean()`.

In [25]:
# Your code here
import pandas as pd

# Create a small CSV for demo
data = """Name,Age,Score
Alice,23,90
Bob,25,85
Charlie,22,95
"""
with open('students.csv', 'w') as f:
    f.write(data)

# Read CSV into a DataFrame
df = pd.read_csv('students.csv')
df

      Name  Age  Score
0    Alice   23     90
1      Bob   25     85
2  Charlie   22     95

In [27]:
df['Score']

0    90
1    85
2    95
Name: Score, dtype: int64

In [28]:
df['Score'].mean()

np.float64(90.0)

### Practice 2 — Filter and Save (medium)
Filter `df` down to only students with a `Score` of 90 or above, then save that filtered DataFrame to `top_students.csv`.

In [ ]:
# Your code here
df[df['Score'] >90]

      Name  Age  Score
2  Charlie   22     95

In [32]:
top_students = df[df['Score'] >90]
top_students.to_csv('top_students.csv', index=False)

### Practice 3 — Read It Back and Verify (harder)
Read `top_students.csv` back into a new DataFrame and confirm (with an `if`/`print`, not just by eyeballing it) that every row in it has a `Score` of 90 or above.

In [33]:
# Your code here
import pandas as pd

# Read the file back into a new DataFrame
check_df = pd.read_csv('top_students.csv')

# Confirm every Score is 90 or above
if (check_df['Score'] >= 90).all():
    print("Success: Every student has a Score of 90 or above.")
else:
    print("Error: Some students have a Score below 90.")

Success: Every student has a Score of 90 or above.

## 🔥 Challenge (Optional) — Handling a Missing File
Combine what you learned in the Functions and Loops modules: write a function `load_data(filename)` that tries to `pd.read_csv(filename)` and returns the DataFrame, but catches `FileNotFoundError` and returns `None` (printing a friendly message) if the file doesn't exist. Test it on `'students.csv'` and on a filename that doesn't exist.

In [ ]:
def load_data(filename):
    # Your code here
    pass

load_data('students.csv')
load_data('does_not_exist.csv')

In [34]:
import pandas as pd

def load_data(filename):
    try:
        df = pd.read_csv(filename)
        print(f"Successfully loaded {filename}")
        return df
    except FileNotFoundError:
        print(f"Sorry, '{filename}' was not found.")
        return None

# Test with an existing file
load_data('students.csv')

# Test with a file that does not exist
load_data('does_not_exist.csv')

try:
    with open('does_not_exist.txt', 'r') as f:
        print(f.read())
except FileNotFoundError:
    print('That file does not exist yet — check the filename and path.')

Successfully loaded students.csv
Sorry, 'does_not_exist.csv' was not found.
That file does not exist yet — check the filename and path.